version: '2.1'
services:
    elastest-platform-manager:
        container_name: elastest-epm
        image: elastest/epm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        expose:
            - 8180
        ports:
            - 8180:8180
        networks:
            - elastest
    epm-adapter-docker:
        container_name: elastest-epm-adapter-docker
        image: elastest/epm-adapter-docker
        entrypoint: java -jar epm-adapter-docker.jar --register-adapter
        depends_on:
            - elastest-platform-manager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        expose: 
            - 50053
        ports:
            - 50053:50053
        networks:
            - elastest
networks:
    elastest:
        driver: bridge
